version: "3"
services:
  db:
    container_name: db-flask_reports
    image: postgres:latest
    user: postgres
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flask_reports
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: "no"
    command: ["postgres", "-c", "log_statement=all", "-c", "log_filename=postgresql-%a.log", "-c", "log_rotation_age=1d", "-c", "log_truncate_on_rotation=on", "-c", "log_min_duration_statement=0"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../../data/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    container_name: redis-flask_reports
    image: redis:latest
    restart: always
    entrypoint: redis-server --appendonly yes --requirepass password --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - default
    ports:
      - "6379:6379"
    volumes:
      - /appdata/redis/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD="password"
volumes:
  pgdata:



  
